server:
  port: 8280
  servlet:
    context-path: /

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8083/auth/realms/partola
          jwk-set-uri: http://localhost:8083/auth/realms/partola/protocol/openid-connect/certs
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa

keycloak:
  server:
    contextPath: /auth
    adminUser:
      username: sa
      password: sa
    realmImportFile: partola-realm.json